# Generated by Django 5.2.9 on 2026-01-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_provider'),
        ('providers', '0002_alter_provider_email_alter_provider_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='providers.provider'),
        ),
    ]
