# Generated by Django 5.2.9 on 2026-01-23 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('domain', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('PUBLISHED', 'Published'), ('IN_NEGOTIATION', 'In Negotiation'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('negotiated_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('response_deadline', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
                ('terms_and_condition', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_requests.servicerequest')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.specialist')),
                ('winning_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_requests.serviceoffer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('counter_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter_offer_explanation', models.TextField(blank=True)),
                ('proposed_terms_and_condition', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
            ],
            options={
                'unique_together': {('contract', 'version_number')},
            },
        ),
    ]
