# Generated by Django 5.2.9 on 2026-01-09 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_status'),
        ('service_requests', '0005_alter_serviceoffer_status_and_more'),
        ('specialists', '0002_remove_specialist_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractversion',
            old_name='comment',
            new_name='counter_offer_explanation',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='commercial_weight',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='functional_weight',
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contractversion',
            name='payload',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='contract',
            name='offered_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='response_deadline',
            field=models.DateField(default=datetime.datetime(2026, 1, 9, 15, 15, 46, 557284, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_and_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='Contract Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='winning_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_requests.serviceoffer'),
        ),
        migrations.AddField(
            model_name='contractversion',
            name='counter_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractversion',
            name='proposed_terms_and_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2026, 1, 9, 15, 16, 30, 325180, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_to',
            field=models.DateField(default=datetime.datetime(2026, 1, 9, 15, 16, 38, 745797, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PricingRule',
        ),
    ]
