# Generated by Django 5.2.9 on 2026-01-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_comment_contractversion_counter_offer_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_for',
        ),
    ]
