# Generated by Django 5.2.9 on 2026-01-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_contract_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='negotiated_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
