# Generated by Django 5.2.9 on 2026-01-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_negotiated_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='offered_daily_rate',
            new_name='proposed_rate',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='valid_to',
            new_name='valid_till',
        ),
        migrations.AddField(
            model_name='contract',
            name='domain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
