# Generated by Django 5.2.9 on 2026-01-23 07:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('specialist_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('role_name', models.CharField(help_text='e.g., Software Engineer, Project Manager', max_length=100)),
                ('experience_level', models.CharField(choices=[('JUNIOR', 'Junior (0-2 years)'), ('MID', 'Mid-Level (3-5 years)'), ('SENIOR', 'Senior (6-10 years)'), ('LEAD', 'Lead (10+ years)'), ('EXPERT', 'Expert/Architect (15+ years)')], max_length=20)),
                ('skills', models.TextField(help_text='Comma-separated skills (e.g., Python, React, AWS)')),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated certifications', null=True)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Frontend, Backend, Full-stack', max_length=200, null=True)),
                ('avg_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On_Leave', 'On Leave')], default='Active', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, help_text='Leave blank if indefinite', null=True)),
                ('max_weekly_hours', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('location', models.CharField(help_text='City, Country', max_length=200)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='Remote', max_length=20)),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('languages_spoken', models.CharField(help_text='Comma-separated languages (e.g., English, Spanish)', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='providers.provider')),
            ],
        ),
    ]
