# Generated by Django 5.2.9 on 2026-01-06 21:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='performance_grade',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='technology_level',
        ),
        migrations.AddField(
            model_name='specialist',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='available_until',
            field=models.DateField(blank=True, help_text='Leave blank if indefinite', null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='certifications',
            field=models.TextField(blank=True, help_text='Comma-separated certifications', null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='languages_spoken',
            field=models.CharField(default=1, help_text='Comma-separated languages (e.g., English, Spanish)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='location',
            field=models.CharField(default='temp@example.com', help_text='City, Country', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='max_weekly_hours',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='specialist',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes', null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='skills',
            field=models.TextField(default='python', help_text='Comma-separated skills (e.g., Python, React, AWS)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialist_code',
            field=models.CharField(default='SPE-0AER', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g., Frontend, Backend, Full-stack', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On_Leave', 'On Leave')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='specialist',
            name='willing_to_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialist',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='Remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience_level',
            field=models.CharField(choices=[('JUNIOR', 'Junior (0-2 years)'), ('MID', 'Mid-Level (3-5 years)'), ('SENIOR', 'Senior (6-10 years)'), ('LEAD', 'Lead (10+ years)'), ('EXPERT', 'Expert/Architect (15+ years)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='role_name',
            field=models.CharField(help_text='e.g., Software Engineer, Project Manager', max_length=100),
        ),
    ]
