# Generated by Django 5.2.9 on 2026-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_remove_substitutionrequest_current_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='supplier_name',
            field=models.CharField(default='Somename', max_length=30),
            preserve_default=False,
        ),
    ]
