# Generated by Django 5.2.9 on 2026-01-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_serviceorder_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='consumed_man_days',
        ),
    ]
