# Generated by Django 5.2.9 on 2026-01-17 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(help_text='Role of the user when action was performed', max_length=50)),
                ('action_category', models.CharField(choices=[('USER_MANAGEMENT', 'User Management'), ('SPECIALIST_MANAGEMENT', 'Specialist Management'), ('OFFER_MANAGEMENT', 'Offer Management'), ('CONTRACT_MANAGEMENT', 'Contract Management'), ('AUTHENTICATION', 'Authentication')], db_index=True, max_length=50)),
                ('action_type', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_DELETED', 'User Deleted'), ('SPECIALIST_CREATED', 'Specialist Created'), ('SPECIALIST_UPDATED', 'Specialist Updated'), ('SPECIALIST_DELETED', 'Specialist Deleted'), ('SPECIALIST_ASSIGNED', 'Specialist Assigned to Service Request'), ('REQUEST_GENERATED', 'Request Generated'), ('OFFER_SUBMITTED', 'Offer Submitted'), ('OFFER_UPDATED', 'Offer Updated'), ('OFFER_WITHDRAWN', 'Offer Withdrawn'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('CONTRACT_ACCEPTED', 'Contract Accepted'), ('CONTRACT_REJECTED', 'Contract Rejected'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('CONTRACT_UPDATED', 'Contract Updated'), ('CONTRACT_COUNTER_OFFER', 'Contract Counter Offer Submitted'), ('CONTRACT_NEGOTIATION_STARTED', 'Contract Negotiation Started'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=50)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending'), ('ERROR', 'Error')], default='SUCCESS', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('entity_type', models.CharField(blank=True, help_text='Type of related object (e.g., Offer, Contract, Specialist)', max_length=50)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the related object', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (e.g., old values, new values,)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_log_a_created_4eb339_idx'), models.Index(fields=['user', '-created_at'], name='audit_log_a_user_id_c0e9bd_idx'), models.Index(fields=['action_category', '-created_at'], name='audit_log_a_action__de6f92_idx'), models.Index(fields=['action_type', '-created_at'], name='audit_log_a_action__fa3e25_idx')],
            },
        ),
    ]
