# Generated by Django 5.2.9 on 2026-01-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_auditlog_actor_role_auditlog_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
