# Generated by Django 5.2.9 on 2025-12-13 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='DRAFT', max_length=16)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_request_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('OPEN', 'Open for offers'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled')], default='IMPORTED', max_length=16)),
                ('domain', models.CharField(max_length=128)),
                ('role_name', models.CharField(max_length=128)),
                ('technology', models.CharField(blank=True, max_length=128)),
                ('experience_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], max_length=16)),
                ('technology_level', models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5')], max_length=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_man_days', models.PositiveIntegerField(blank=True, null=True)),
                ('criteria_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
