# Generated by Django 5.2.9 on 2026-01-23 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('role_name', models.CharField(max_length=128)),
                ('technology', models.CharField(blank=True, max_length=128)),
                ('specialization', models.CharField(blank=True, max_length=64)),
                ('experience_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior (0-2 years)'), ('MID', 'Mid-Level (3-5 years)'), ('SENIOR', 'Senior (6-10 years)'), ('LEAD', 'Lead (10+ years)'), ('EXPERT', 'Expert/Architect (15+ years)')], max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_man_days', models.PositiveIntegerField(blank=True, null=True)),
                ('criteria_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('OPEN', 'Open for offers'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('task_description', models.TextField(blank=True)),
                ('offer_deadline', models.DateField(blank=True, null=True)),
                ('word_mode', models.CharField(blank=True, default='Remote', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='SUBMITTED', max_length=16)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.specialist')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='providers.provider')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='service_requests.servicerequest')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='service_req_provide_8c29a5_idx'), models.Index(fields=['request', 'status'], name='service_req_request_6947a7_idx')],
            },
        ),
    ]
