# Generated by Django 5.2.9 on 2025-12-13 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='proposed_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='service_requests.servicerequest'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['provider', 'status'], name='service_req_provide_8c29a5_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffer',
            index=models.Index(fields=['request', 'status'], name='service_req_request_6947a7_idx'),
        ),
    ]
