# Generated by Django 5.2.9 on 2025-12-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='criteria_json',
        ),
    ]
