# Generated by Django 5.2.9 on 2025-12-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_remove_servicerequest_criteria_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='criteria_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
