# Generated by Django 5.2.9 on 2026-01-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_servicerequest_criteria_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='SUBMITTED', max_length=16),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior (0-2 years)'), ('MID', 'Mid-Level (3-5 years)'), ('SENIOR', 'Senior (6-10 years)'), ('LEAD', 'Lead (10+ years)'), ('EXPERT', 'Expert/Architect (15+ years)')], max_length=16),
        ),
    ]
