# Generated by Django 5.2.9 on 2026-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_alter_serviceoffer_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='domain',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technology_level',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='offer_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='specialization',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='word_mode',
            field=models.CharField(blank=True, default='Remote', max_length=16),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('OPEN', 'Open for offers'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16),
        ),
    ]
