# Generated by Django 5.2.9 on 2026-01-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_rename_domain_servicerequest_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='external_request_id',
            new_name='external_id',
        ),
    ]
